title: Tech Summary Blog
description: テック記事の要約を日々お届けするブログ
url: "https://tyamauchi-gao.github.io"
baseurl: ""

theme: minima

markdown: kramdown
permalink: /:year/:month/:day/:title/

show_excerpts: true
excerpt_separator: "---"

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
